// core/hmr-client/src/components/Panel/index.tsx
import { h, JSX } from "preact";
import { useState, useEffect } from "preact/hooks";
import style from './style.module.css'
import uniqueId from 'lodash/uniqueId';
import { Item } from '../Item'
import type { ResultItems } from '@veva/utils/webpackStats'

export const Panel = (props: {
  warnings: Array<ResultItems>,
  errors: Array<ResultItems>
}): JSX.Element => {
  const [ key, setKey ] = useState(uniqueId('key'));
  const [ items, setItems ] = useState(props.errors);
  const [ select, setSelect ] = useState('errors');
  const [ open, setOpen ] = useState(true);

  const collapseAll = () => {
    setOpen(false)
    setKey(uniqueId('key'))
  }
  
  const expandAll = () => {
    setOpen(true)
    setKey(uniqueId('key'))
  }

  const onSelect = (value: 'errors' | 'warnings') => {
    setSelect(value)
    switch (value) {
      case 'errors':
        setItems(props.errors)
      break;
      case 'warnings':
        setItems(props.warnings)
      break;
    }
  }

  return (
  <div className={style['panel']}>
    <div className={style['panel-tabs']}>
      <div onClick={()=>onSelect('errors')} className={[style['tab-item'], select === 'errors' && style['tab-item-active']].join(' ')}>
        Errors ({props.errors.length})
      </div>
      <div onClick={()=>onSelect('warnings')} className={[style['tab-item'], select === 'warnings' && style['tab-item-active']].join(' ')}>
        Warnings ({props.warnings.length})
      </div>
    </div>
    <div className={style['panel-body']}>
      <div className={style['panel-header']}>
        <div className={style['panel-header-action']}>
          <div onClick={collapseAll} className={style['button']}>Collapse all</div>
          <div onClick={expandAll} className={style['button']}>Expand All</div>
        </div>
      </div>

      <div key={key} className={style['panel-content']}>
        {items.map(function({ title, message }, i){
          return <Item title={title} message={message} open={open} />;
        })}
      </div>
    </div>
  </div>)
};

// core/hmr-client-svelte/src/components/Panel.svelte
<script lang="ts">
export let errors;
export let warnings;
import Item from "./Item.svelte";
import uniqueId from 'lodash/uniqueId';

$: open = false;
$: select = 'errors';
$: key = uniqueId('key');

const collapseAll = () => {
  open = false;
  key = uniqueId('key');
}

const expandAll = () => {
  open = true;
  key = uniqueId('key');
}

let items = errors;
const onSelect = (value: 'errors' | 'warnings') => {
  select = value;
  switch (value) {
    case 'errors':
    items = errors
    break;
    case 'warnings':
    items = warnings
    break;
  }
}
</script>

<style>
.panel {
  transform: translate3d(0, 0, 0);
  margin-top: 20px;
  margin-bottom: 20px;
}

.panel-body {
  background: #2a344c;
}

.panel-content {
  padding: 10px;
}

.panel-tabs {
  display: flex;
  background: #1f2538;
}

.tab-item {
  padding: 15px;
  cursor: pointer;
}

.tab-item-active {
  background: #2a344c;
}

/* -------------------- */
.panel-header {
  padding: 15px;
  padding-bottom: 0;
  display: flex;
}

.action {
  flex-grow: 1;
}

.button {
  margin: 0 2px;
  cursor: pointer;
  padding: 5px;
  position: relative;
  display: inline-block;
  border: 1px solid #fff;
}
</style>

<template>
  <div class="panel">
    <div class="panel-tabs">
      {#if warnings.length}
        <div
          on:click={() =>onSelect('errors')}
          class="{select === 'errors' ? 'tab-item tab-item-active' : 'tab-item'}"
        >
          Errors ({errors.length})
        </div>
        <div
          on:click={() =>onSelect('warnings')}
          class="{select === 'warnings' ? 'tab-item tab-item-active' : 'tab-item'}"
        >
        Warnings ({warnings.length})
        </div>
      {/if}
    </div>
    <div class="panel-body">
      <div class="panel-header">
        <div class="action">
          <div on:click={collapseAll} class="button">Collapse all</div>
          <div on:click={expandAll} class="button">Expand All</div>
        </div>
      </div>
      <div class="panel-content">
        {#key key}
          {#each items as { title, message }}
            {#key message}
            <Item title={title} message={message} open={open}/>
            {/key}
          {/each}
        {/key}
      </div>
    </div>
  </div>
</template>
